# Generated by Django 5.2.15 on 2026-07-17 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('module_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('manifest_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=255)),
                ('module_id', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('tenant_id', 'module_id')},
            },
        ),
    ]
