# Generated by Django 5.2.16 on 2026-07-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill')], default='invoice', max_length=50),
        ),
    ]
