import React from "react";
import { motion, useScroll, useTransform } from "framer-motion";
import { useNavigate } from "react-router-dom";
import {
  Sparkles,
  ArrowRight,
  Server,
  ShieldCheck,
  Zap,
  Users,
  Settings,
  Moon,
  Sun,
} from "lucide-react";
import { useAuth } from "../context/AuthContext";

export function HeroPage() {
  const navigate = useNavigate();
  const { themeMode, toggleThemeMode } = useAuth();
  const { scrollYProgress } = useScroll();
  const y = useTransform(scrollYProgress, [0, 1], ["0%", "50%"]);

  return (
    <div className="min-h-screen bg-slate-100 dark:bg-background flex flex-col relative overflow-hidden">
      {/* Background Effects */}
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/10 via-background to-background" />
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-primary/30 blur-[120px] rounded-full pointer-events-none animate-pulse mix-blend-multiply dark:mix-blend-screen" />

      {/* Navigation */}
      <nav className="relative z-50 flex items-center justify-between p-6 max-w-7xl mx-auto w-full">
        <div className="flex items-center gap-3">
          <img
            src="/logo.png"
            alt="NexusERP"
            className="w-10 h-10 object-contain drop-shadow-md"
          />
          <span className="font-extrabold text-2xl tracking-tight text-foreground">
            NexusERP
          </span>
        </div>
        <div className="flex items-center gap-4">
          <button
            onClick={toggleThemeMode}
            className="w-10 h-10 rounded-full bg-white/50 dark:bg-black/50 border border-border flex items-center justify-center text-foreground hover:bg-accent transition-colors shadow-sm"
            aria-label="Toggle theme"
          >
            {themeMode === "dark" ? (
              <Sun className="w-5 h-5" />
            ) : (
              <Moon className="w-5 h-5" />
            )}
          </button>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => navigate("/login")}
            className="px-5 py-2.5 rounded-full font-semibold text-sm bg-primary/10 text-primary hover:bg-primary hover:text-primary-foreground transition-all duration-300 shadow-sm shadow-primary/20"
          >
            Sign In / Portal
          </motion.button>
        </div>
      </nav>

      {/* Hero Content */}
      <main className="relative z-10 flex-1 flex flex-col items-center justify-center text-center px-4 pt-20 pb-32">
        <motion.div
          initial={{ scale: 0.8, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ duration: 0.5 }}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-bold mb-8 border border-primary/20"
        >
          <Sparkles className="w-4 h-4" />
          The Next Generation AI ERP Platform
        </motion.div>

        <motion.h1
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.2, duration: 0.6 }}
          className="text-5xl md:text-7xl font-black tracking-tighter max-w-4xl text-foreground drop-shadow-sm leading-tight mb-6"
        >
          Intelligent Operations, <br />
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-purple-600">
            Generated by AI.
          </span>
        </motion.h1>

        <motion.p
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.4, duration: 0.6 }}
          className="text-lg md:text-xl text-muted-foreground font-medium max-w-2xl mb-12"
        >
          Build, scale, and manage your entire business infrastructure
          instantly. NexusERP builds customized internal tools powered by
          artificial intelligence.
        </motion.p>

        <motion.div
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.6, duration: 0.6 }}
          className="flex flex-col sm:flex-row items-center gap-4"
        >
          <motion.button
            whileHover={{
              scale: 1.05,
              boxShadow: "0px 10px 40px -10px rgba(59, 130, 246, 0.8)",
            }}
            whileTap={{ scale: 0.95 }}
            onClick={() =>
              navigate("/login", { state: { isRegistering: true } })
            }
            className="relative overflow-hidden group px-8 py-4 rounded-full font-bold text-lg text-white shadow-xl flex items-center gap-2 border border-white/20"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-blue-600 via-indigo-500 to-purple-600 group-hover:opacity-90 transition-opacity" />
            <div className="absolute inset-0 opacity-0 group-hover:opacity-100 bg-[linear-gradient(to_right,transparent,rgba(255,255,255,0.2),transparent)] -translate-x-full group-hover:translate-x-full transition-all duration-1000 ease-in-out" />
            <span className="relative z-10 flex items-center gap-2">
              Get Started{" "}
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </span>
          </motion.button>

          <motion.button
            whileHover={{
              scale: 1.05,
              backgroundColor: "rgba(255,255,255,0.8)",
            }}
            whileTap={{ scale: 0.95 }}
            onClick={() => navigate("/login")}
            className="px-8 py-4 rounded-full font-bold text-lg bg-white/50 backdrop-blur-md text-foreground shadow-sm hover:shadow-md transition-all flex items-center gap-2 border border-border hover:border-primary/30"
          >
            Access Portal
          </motion.button>
        </motion.div>
      </main>

      {/* Feature Grid */}
      <motion.div
        initial={{ y: 40, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.8, duration: 0.8 }}
        className="relative z-10 pb-20 px-6"
      >
        <div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6">
          {[
            {
              icon: Zap,
              title: "Instant Generation",
              desc: "AI builds your custom modules in seconds, not months.",
            },
            {
              icon: Server,
              title: "Centralized Data",
              desc: "A unified platform connecting every department seamlessly.",
            },
            {
              icon: ShieldCheck,
              title: "Enterprise Grade",
              desc: "Secure, scalable infrastructure ready for any scale.",
            },
          ].map((feature, i) => (
            <motion.div
              whileHover={{ y: -5 }}
              key={i}
              className="glass-panel p-6 rounded-3xl border border-primary/10 hover:border-primary/40 transition-colors shadow-sm"
            >
              <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center mb-4 text-primary">
                <feature.icon className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
              <p className="text-muted-foreground">{feature.desc}</p>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* How it Works Section (Scrolling Content) */}
      <section className="relative z-10 py-32 bg-surface-alt/50 border-t border-border/40">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-extrabold tracking-tight mb-4">
              How NexusERP Works
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              From idea to full deployment in three simple steps.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
            {[
              {
                icon: Sparkles,
                step: "01",
                title: "Describe Your Business",
                desc: "Tell our AI about your industry, company size, and specific operational needs.",
              },
              {
                icon: Settings,
                step: "02",
                title: "AI Generation",
                desc: "The engine instantly provisions databases, workflows, and tailored UI modules.",
              },
              {
                icon: Users,
                step: "03",
                title: "Deploy & Scale",
                desc: "Invite your team and start managing your operations immediately with zero setup time.",
              },
            ].map((step, i) => (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ delay: i * 0.2, duration: 0.6 }}
                key={i}
                className="relative text-center flex flex-col items-center"
              >
                <div className="text-8xl font-black text-primary/5 absolute -top-10 -z-10">
                  {step.step}
                </div>
                <div className="w-20 h-20 rounded-full bg-background border border-border shadow-lg flex items-center justify-center text-primary mb-6">
                  <step.icon className="w-8 h-8" />
                </div>
                <h3 className="text-2xl font-bold mb-3">{step.title}</h3>
                <p className="text-muted-foreground">{step.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 border-t border-border/20 bg-background py-12 px-6 text-center text-muted-foreground">
        <div className="max-w-7xl mx-auto flex flex-col items-center justify-center gap-4">
          <div className="flex items-center gap-2 mb-2">
            <img
              src="/logo.png"
              alt="Logo"
              className="w-6 h-6 grayscale opacity-60"
            />
            <span className="font-bold text-lg opacity-60">NexusERP AI</span>
          </div>
          <p className="text-sm">
            &copy; {new Date().getFullYear()} NexusERP AI. All rights reserved.
          </p>
          <div className="flex gap-4 mt-4 text-sm font-medium">
            <a href="#" className="hover:text-primary transition-colors">
              Privacy Policy
            </a>
            <a href="#" className="hover:text-primary transition-colors">
              Terms of Service
            </a>
            <a href="#" className="hover:text-primary transition-colors">
              Contact
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
