import React, { useState, useEffect } from "react";
import axios from "axios";
import { useAuth } from "../context/AuthContext";
import {
  Bell,
  CheckCheck,
  Package,
  CalendarClock,
  Receipt,
} from "lucide-react";

import { API_BASE } from "../config";

export function NotificationsDashboard() {
  const { token, themeColor } = useAuth();
  const [notifications, setNotifications] = useState([]);
  const [isFetching, setIsFetching] = useState(true);

  const fetchData = async () => {
    setIsFetching(true);
    try {
      const res = await axios.get(`${API_BASE}/api/notifications/`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setNotifications(res.data);
    } catch (err) {
      console.error("Failed to fetch notifications", err);
    } finally {
      setIsFetching(false);
    }
  };

  useEffect(() => {
    if (token) fetchData();
  }, [token]);

  const handleMarkRead = async (id) => {
    try {
      await axios.post(
        `${API_BASE}/api/notifications/${id}/mark_read/`,
        {},
        { headers: { Authorization: `Bearer ${token}` } },
      );
      setNotifications(
        notifications.map((n) => (n.id === id ? { ...n, is_read: true } : n)),
      );
    } catch (err) {
      console.error("Failed to mark read", err);
    }
  };

  const getIcon = (type) => {
    switch (type) {
      case "stock_alert":
        return <Package className="w-5 h-5 text-orange-500" />;
      case "reminder":
        return <CalendarClock className="w-5 h-5 text-blue-500" />;
      case "invoice":
        return <Receipt className="w-5 h-5 text-red-500" />;
      default:
        return <Bell className="w-5 h-5 text-gray-500" />;
    }
  };

  const unreadCount = notifications.filter((n) => !n.is_read).length;

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fade-in relative z-10 p-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight text-foreground flex items-center gap-3">
            System Feed
            {unreadCount > 0 && (
              <span
                className="px-2.5 py-0.5 rounded-full text-sm font-bold bg-primary text-white"
                style={{ backgroundColor: themeColor }}
              >
                {unreadCount} New
              </span>
            )}
          </h1>
          <p className="text-muted-foreground mt-1">
            Review alerts, reminders, and updates generated by the system.
          </p>
        </div>
      </div>

      <div className="glass-panel rounded-2xl overflow-hidden border border-transparent hover:border-primary/20 transition-all duration-300">
        {isFetching ? (
          <div className="p-12 flex justify-center">
            <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin" />
          </div>
        ) : notifications.length === 0 ? (
          <div className="p-16 text-center">
            <Bell className="w-12 h-12 mx-auto text-muted-foreground/30 mb-4" />
            <h3 className="text-xl font-bold text-foreground">
              You're all caught up!
            </h3>
            <p className="text-muted-foreground mt-2">
              No new notifications in your feed right now.
            </p>
          </div>
        ) : (
          <div className="divide-y divide-border/50">
            {notifications.map((n) => (
              <div
                key={n.id}
                className={`p-5 flex gap-4 transition-colors ${n.is_read ? "bg-transparent opacity-60 hover:opacity-100" : "bg-primary/5"}`}
              >
                <div className="mt-1 shrink-0 bg-background p-2 rounded-xl shadow-sm border border-border/50">
                  {getIcon(n.notification_type)}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2">
                    <h4
                      className={`font-bold truncate ${n.is_read ? "text-muted-foreground" : "text-foreground"}`}
                    >
                      {n.title}
                    </h4>
                    <span className="text-xs text-muted-foreground whitespace-nowrap">
                      {new Date(n.created_at).toLocaleString()}
                    </span>
                  </div>
                  <p
                    className={`mt-1 text-sm ${n.is_read ? "text-muted-foreground" : "text-foreground/90"}`}
                  >
                    {n.message}
                  </p>
                </div>
                {!n.is_read && (
                  <button
                    onClick={() => handleMarkRead(n.id)}
                    className="shrink-0 self-center p-2 rounded-full hover:bg-muted text-muted-foreground hover:text-primary transition-colors"
                    title="Mark as read"
                  >
                    <CheckCheck className="w-5 h-5" />
                  </button>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
