# Generated by Django 5.2.16 on 2026-07-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(default='direct', max_length=50),
        ),
    ]
