# Generated by Django 5.2.15 on 2026-07-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forged_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
