# Generated by Django 5.2.15 on 2026-07-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forged_auth', '0002_user_assigned_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
