# Generated by Django 5.2.15 on 2026-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forged_auth', '0003_business_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ai_prompt',
            field=models.TextField(blank=True),
        ),
    ]
