# Generated by Django 5.2.16 on 2026-08-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forged_auth', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
