# Generated by Django 5.2.16 on 2026-07-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_order_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
