# Generated by Django 5.2.15 on 2026-07-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('forged_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='forged_auth.business'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('tenant', 'employee_id', 'date')},
        ),
    ]
