# Generated by Django 5.2.15 on 2026-07-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barcode_catalog', '0001_initial'),
        ('forged_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='forged_auth.business'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='forged_auth.business'),
        ),
        migrations.AddField(
            model_name='barcode',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='barcode_catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_locations', to='forged_auth.business'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='barcode_catalog.storelocation'),
        ),
    ]
